### ISSUE TITLE
How many app server that dokku can have as its sub domain?

### ISSUE THREAD

**Issue by Hemalatah** [gauravmehla/ama#4]
Hi Gaurav Mehla,

First of all, Thank you so much for this wonderful article. There is no sufficient resources available to learn this concept at this moment. I am planning to host multiple app server(approx. 1000s) for the main web server. Would that be possible with dokku?? That too would be like the architectural style of google like 'google.com' web server has multiple apps such as 'mail.google.com', 'console.google.com', 'meet.google.com'....

Thanks in advance for your thoughts and suggestions.
Appreciate your time and help!
Hema

**Comment by gauravmehla** [comment]
Hey @hemalatah,

First of all, I have created maximum ~20 subdomain and *dokku* can handle this much of applications easily. I never tried for this much large scale (1000's)

As far as I have knowledge of this whole architecture, I think you can add as much as subdomain you want but the only limitation is going to be the main machine or the server on which you are running *dokku*. Basically, every app in *dokku* is a little container and running 1000's of container on one machine is going to be an enormous task. Instead of that I will suggest you to make clusters and use kubernetes to manage these containers.

**Comment by Hemalatah** [comment]
Thanks for your quick response. One more questions, If I use kubernetes clusters, does it support all the modern database services like mongoDB, Mysql...

**Comment by gauravmehla** [comment]
See, Kubernetes are just to manage Docker containers and your applications will run inside those containers. So, the connection with the database mainly depends on your application, not on Kubernetes or container.

![Imgur](https://i.imgur.com/IC1FFvH.jpg)

This graphic may give you an idea.

**Comment by Hemalatah** [comment]
Thanks a bunch! I got some idea now!!
